module.exports = [{
  uuid: '1',
  typeId: 'env',
  name: 'Environmental Control',
  remark: '',
  create_date: Date.now(),
  last_modify_date: Date.now(),
},
{
  uuid: '2',
  typeId: 'mac',
  name: 'machinery',
  remark: '',
  create_date: Date.now(),
  last_modify_date: Date.now(),
},
{
  uuid: '3',
  typeId: 'air',
  name: 'Air Compressor',
  remark: '',
  create_date: Date.now(),
  last_modify_date: Date.now(),
},{
  uuid: '4',
  typeId: 'ele',
  name: 'Electricity Meter',
  remark: '',
  create_date: Date.now(),
  last_modify_date: Date.now(),
}];
